### ISSUE TITLE
Synology Note Station nsx to MD issues (Table is too complex, URI malformed etc)

### ISSUE THREAD

**Issue by maximrimet** [marph91/jimmy#27]
**Describe the Bug**

There are several issues when exporting Synology Note Station (`.nsx`) files to Markdown (`.md`) with front matter using Jimmy:

1. **Embedded YouTube Links**:
   - The tool does not handle embedded YouTube links properly, often resulting in the error: `Could not fetch resource`.

2. **Complex Tables**:
   - Notes with links in the headers frequently cause the warning: `Table is too complex and can't be converted to markdown`. After this, tables are exported as plain text or fail entirely.

3. **Missing Images**:
   - Following the table conversion warning, images in notes are incorrectly linked as:  
     `![](webman/3rdparty/NoteStation/images/transparent.gif)`  
     This makes all images unusable after export.

4. **Import Issues**:
   - Attempting to import the folder of exported `.md` files into Joplin results in the error: `URI malformed`.

5. **Table Conversion**:
   - Some tables are not exported properly to Markdown and instead are converted as plain text, losing their structure.

6. **Issues with Special Characters**:
   - Notes containing special characters like `Ó`, `Ń`, etc., result in improper rendering or errors during the export and import process.

**OS and Environment**
- **Operating System**: Windows 11
- **Source Application**: Synology Note Station
- **Command Used**:
  ```bash
  jimmy-cli-windows.exe test8.nsx --format synology_note_station --frontmatter joplin --stdout-log-level DEBUG

**Comment by marph91** [comment]
Thanks for the detailed report! I will try to answer all the points:

1. **Embedded YouTube Links:** Iframes are removed by pandoc. I implemented a workaround, so that they are converted to plain links at least. NB: In Joplin, [iframes aren't supported](https://discourse.joplinapp.org/t/how-to-use-iframe-tag-and-render-in-joplin/32421) anyway.

2. **Complex Tables:** In general, Markdown pipe tables don't support any complex formatting (i. e. multiline). Looking at the specific tables:
    1. In `KRAKÓW - Duplicate`: This is not a "classic" HTML table and it's nested. The last column (starting with "Telefon") is a table inside the table. Unfortunately, this can't be converted to a Markdown pipe table trivially.
    2. In `quotation`: The table contained newlines. The conversion is more robust now and can handle it.
    3. In `Продажа Ford Focus 2 2008 Харьков. Ford Focus Харьков на Автобазаре. ID: 1-2254593-1`: There is a list inside the table. This isn't supported in Markdown, so I replaced it with plain characters (`- `).
    4. I couldn't find an example table with links in headers. I suppose this isn't a problem.

3. **Missing Images:** This issue was observed [here](https://discourse.joplinapp.org/t/jimmy-a-joplin-import-tool/38503/9), but I don't have a reproducer. If you could provide an export file with this error, I can take a deeper look.

4. **Import Issues:** This was observed [here](https://discourse.joplinapp.org/t/jimmy-a-joplin-import-tool/38503/9), too. The root cause is unclear. Later it was reported that the notes were imported properly, even when the error occured.

5. **Table Conversion:** See 2.

6. **Issues with Special Characters:** I couldn't observe this in your example file (and also not at the other test files that contain `Ö` for example). Maybe this is not a real issue, but a follow-up from the other issues?

---

I prepared a [release](https://github.com/marph91/jimmy/releases/tag/v0.0.40) with the mentioned improvements. Just as reference. This is how the imported example file looks currently:

![grafik](https://github.com/user-attachments/assets/a212b08e-213b-4633-b6d7-061218515605)

---

Side note: If you rely on complex tables, Markdown might not be the best format for you (or you need to find some Markdown flavor that supports multiline tables). If you still want to use Markdown, I would recommend to structure the tables in a simpler way.

**Comment by maximrimet** [comment]
Thank you for your quick response
I checked the new release, the warning "Table is too complex" is gone, but still have the issue with transparent.gif and URI Malformed
The test file to reproduce the problem is uploaded [here](https://drive.google.com/file/d/1QV2gBRAIZ3iHwxiaPxvj1VLiZLu4DcpM/view?usp=sharing). Please do not share it to public

**Comment by marph91** [comment]
> The test file to reproduce the problem is uploaded [here](https://drive.google.com/file/d/1QV2gBRAIZ3iHwxiaPxvj1VLiZLu4DcpM/view?usp=sharing). Please do not share it to public

Thanks. I downloaded the file and will look at it later today. You can remove the link.

**Comment by marph91** [comment]
You can try the new release: https://github.com/marph91/jimmy/releases/tag/v0.0.41

Regarding the open issues:

- Most of the missing images should be available now. There are still 4 images missing, but they are even missing if I import the `.nsx` file in Note Station. (This is a likely bug in the file export and can only be resolved by Synology. My assumption is, it's because they reference files by MD5 checksum. If a file gets updated, the actual checksum changes, but the old checksum is still referenced and doesn't get updated.)
- `URI malformed`: I think this dialog can be ignored. I created a [forum thread](https://discourse.joplinapp.org/t/improve-the-uri-malformed-import-dialog/42860) to discuss if the dialog can be made more user friendly.

**Comment by maximrimet** [comment]
Thank you for your work on eliminating the bugs. There is still an issue with the images. Some images are missing due to a bug in the Synology export process. However, there are others that exist in the export folder (I can see them there after running the script) but are still missing after being imported into Joplin.

Please check [here](https://drive.google.com/file/d/1I0FsNoNlcz-kE9KaXF47K5nyh7gNFZ8H/view?usp=drive_link) for details (two screenshots are included as examples). Please let me know when you upload the file

**Comment by marph91** [comment]
Update: The `URI malformed` issue (including missing images) is fixed in [pre-release 3.2.9](https://github.com/laurent22/joplin/releases/tag/v3.2.9).

**Comment by marph91** [comment]
Hi, are there any issues left or can the issue be closed?

**Comment by maximrimet** [comment]
> Hi, are there any issues left or can the issue be closed?

Yes. Thank you. Please close
